In [1]:
import numpy as np
import pandas as pd

In [2]:
float_data  = pd.Series([1.2, -3.5, np.nan, 0])

In [3]:
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [4]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [5]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])

In [6]:
string_data

0    aardvark
1         NaN
2        None
3     avocado
dtype: object

In [7]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [8]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])

In [9]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [10]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [11]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [12]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
   ....:                      [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])

In [13]:
data

,0,1,2
0,1.0,6.5,3.0
1,1.0,NaN,NaN
2,NaN,NaN,NaN
3,NaN,6.5,3.0


In [14]:
data.dropna()

,0,1,2
0,1.0,6.5,3.0


In [15]:
data.dropna(how = "all")

,0,1,2
0,1.0,6.5,3.0
1,1.0,NaN,NaN
3,NaN,6.5,3.0


In [16]:
data[4] = np.nan

In [17]:
data

,0,1,2,4
0,1.0,6.5,3.0,NaN
1,1.0,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN
3,NaN,6.5,3.0,NaN


In [19]:
data.dropna(axis= 'columns', how= "all")

,0,1,2
0,1.0,6.5,3.0
1,1.0,NaN,NaN
2,NaN,NaN,NaN
3,NaN,6.5,3.0


In [20]:
df = pd.DataFrame(np.random.standard_normal((7, 3)))

In [21]:
df

,0,1,2
0,0.346911,0.552178,-0.662705
1,1.198491,0.352802,-0.232543
2,0.401484,0.757206,-0.593510
3,-2.184147,0.167930,1.152127
4,0.363042,1.120239,-1.761055
5,0.054134,0.351588,0.182748
6,0.592912,-0.112513,-0.694967


In [22]:
df.iloc[:4, 1] = np.nan

In [23]:
df

,0,1,2
0,0.346911,NaN,-0.662705
1,1.198491,NaN,-0.232543
2,0.401484,NaN,-0.593510
3,-2.184147,NaN,1.152127
4,0.363042,1.120239,-1.761055
5,0.054134,0.351588,0.182748
6,0.592912,-0.112513,-0.694967


In [24]:
df.iloc[:2, 2] = np.nan

In [25]:
df

,0,1,2
0,0.346911,NaN,NaN
1,1.198491,NaN,NaN
2,0.401484,NaN,-0.593510
3,-2.184147,NaN,1.152127
4,0.363042,1.120239,-1.761055
5,0.054134,0.351588,0.182748
6,0.592912,-0.112513,-0.694967


In [27]:
df.dropna(thresh= 2)

,0,1,2
2,0.401484,NaN,-0.593510
3,-2.184147,NaN,1.152127
4,0.363042,1.120239,-1.761055
5,0.054134,0.351588,0.182748
6,0.592912,-0.112513,-0.694967


In [28]:
df.fillna(0)

,0,1,2
0,0.346911,0.000000,0.000000
1,1.198491,0.000000,0.000000
2,0.401484,0.000000,-0.593510
3,-2.184147,0.000000,1.152127
4,0.363042,1.120239,-1.761055
5,0.054134,0.351588,0.182748
6,0.592912,-0.112513,-0.694967


In [29]:
df.fillna({1:0.5, 2:0})

,0,1,2
0,0.346911,0.500000,0.000000
1,1.198491,0.500000,0.000000
2,0.401484,0.500000,-0.593510
3,-2.184147,0.500000,1.152127
4,0.363042,1.120239,-1.761055
5,0.054134,0.351588,0.182748
6,0.592912,-0.112513,-0.694967


In [34]:
df.bfill(limit= 2)

,0,1,2
0,0.346911,NaN,-0.593510
1,1.198491,NaN,-0.593510
2,0.401484,1.120239,-0.593510
3,-2.184147,1.120239,1.152127
4,0.363042,1.120239,-1.761055
5,0.054134,0.351588,0.182748
6,0.592912,-0.112513,-0.694967


In [35]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"],
   ....:                      "k2": [1, 1, 2, 3, 3, 4, 4]})

In [36]:
data

,k1,k2
0,one,1
1,two,1
2,one,2
3,two,3
4,one,3
5,two,4
6,two,4


In [37]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [38]:
data.drop_duplicates()

,k1,k2
0,one,1
1,two,1
2,one,2
3,two,3
4,one,3
5,two,4


In [39]:
data['v1'] = range(7)

In [40]:
data

,k1,k2,v1
0,one,1,0
1,two,1,1
2,one,2,2
3,two,3,3
4,one,3,4
5,two,4,5
6,two,4,6


In [42]:
data.drop_duplicates(subset= ['k1'])

,k1,k2,v1
0,one,1,0
1,two,1,1


In [44]:
data.drop_duplicates(['k1', 'k2'], keep= 'last')

,k1,k2,v1
0,one,1,0
1,two,1,1
2,one,2,2
3,two,3,3
4,one,3,4
6,two,4,6


In [45]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
   ....:                               "pastrami", "corned beef", "bacon",
   ....:                               "pastrami", "honey ham", "nova lox"],
   ....:                      "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [46]:
data

,food,ounces
0,bacon,4.0
1,pulled pork,3.0
2,bacon,12.0
3,pastrami,6.0
4,corned beef,7.5
5,bacon,8.0
6,pastrami,3.0
7,honey ham,5.0
8,nova lox,6.0


In [47]:
meat_to_animal = {
  "bacon": "pig",
  "pulled pork": "pig",
  "pastrami": "cow",
  "corned beef": "cow",
  "honey ham": "pig",
  "nova lox": "salmon"
}

In [48]:
data['animal'] = data['food'].map(meat_to_animal)

In [49]:
data

,food,ounces,animal
0,bacon,4.0,pig
1,pulled pork,3.0,pig
2,bacon,12.0,pig
3,pastrami,6.0,cow
4,corned beef,7.5,cow
5,bacon,8.0,pig
6,pastrami,3.0,cow
7,honey ham,5.0,pig
8,nova lox,6.0,salmon


In [51]:
def get_animal(x):
    return meat_to_animal[x]

In [52]:
data['food'].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [53]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [54]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [57]:
data.replace([-999,-1000], [np.nan,0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [58]:
data.replace(
    {
        -999: np.nan,
        -1000:0
    }
)

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [59]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
   ....:                     index=["Ohio", "Colorado", "New York"],
   ....:                     columns=["one", "two", "three", "four"])

In [60]:
data

,one,two,three,four
Ohio,0,1,2,3
Colorado,4,5,6,7
New York,8,9,10,11


In [61]:
def transform(x):
    return x[:4].upper()

In [64]:
data.index = data.index.map(transform)

In [65]:
data

,one,two,three,four
OHIO,0,1,2,3
COLO,4,5,6,7
NEW,8,9,10,11


In [66]:
data.rename(index = str.title, columns= str.upper)

,ONE,TWO,THREE,FOUR
Ohio,0,1,2,3
Colo,4,5,6,7
New,8,9,10,11


In [68]:
data.rename(
    index= {'OHIO': 'INDIANA'},
    columns= {"three": "peekaboo"}
)

,one,two,peekaboo,four
INDIANA,0,1,2,3
COLO,4,5,6,7
NEW,8,9,10,11


In [75]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [76]:
ages

[20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [77]:
bins = [18, 25, 35, 60, 100]

In [78]:
age_cat = pd.cut(ages, bins)

In [79]:
age_cat

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [80]:
age_cat.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [81]:
age_cat.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [83]:
age_cat.categories[0]

Interval(18, 25, closed='right')

In [90]:
age_cat.value_counts()

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [91]:
pd.cut(ages, bins, right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [92]:
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]

In [93]:
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [94]:
data = np.random.uniform(size=20)

In [95]:
data

array([0.14586462, 0.88213713, 0.03363717, 0.41365454, 0.48705485,
       0.36986588, 0.23157448, 0.88752202, 0.69753177, 0.85468093,
       0.51494557, 0.35286974, 0.23928458, 0.27206977, 0.04245802,
       0.61881133, 0.10907983, 0.30542868, 0.44101308, 0.51566721])

In [96]:
pd.cut(data, 4, precision= 2)

[(0.033, 0.25], (0.67, 0.89], (0.033, 0.25], (0.25, 0.46], (0.46, 0.67], ..., (0.46, 0.67], (0.033, 0.25], (0.25, 0.46], (0.25, 0.46], (0.46, 0.67]]
Length: 20
Categories (4, interval[float64, right]): [(0.033, 0.25] < (0.25, 0.46] < (0.46, 0.67] < (0.67, 0.89]]

In [97]:
data = np.random.standard_normal(1000)


In [98]:
data

array([ 9.89126011e-01,  7.47263530e-01,  1.46109773e+00, -1.20716704e+00,
       -1.35051911e-01,  2.14621174e+00,  4.52595871e-01,  8.60045901e-01,
       -2.04101242e+00,  7.01472503e-01,  6.95340197e-01,  7.30139089e-01,
       -1.45290413e-01,  4.24279872e-01,  1.30562677e+00,  7.48195950e-01,
        7.97131615e-01,  5.91215775e-01,  1.01668587e-01, -5.36715107e-01,
        2.41314933e+00, -1.12188092e+00, -1.31946300e+00,  8.44368544e-01,
       -7.30812660e-01, -3.42249988e-02, -1.77952982e+00, -3.99282054e-01,
        1.17029773e+00, -8.35951663e-01, -1.85217061e-01,  7.42378204e-01,
       -1.39732862e+00,  7.89133550e-01, -8.19401227e-01, -3.23177213e-01,
        2.08029504e+00, -1.15056029e+00,  7.69706960e-02, -1.23924213e-01,
        5.73455634e-01, -1.31107130e+00, -4.50295084e-01, -4.50827710e-01,
        1.51943894e+00, -7.75036595e-03,  1.60468066e+00,  1.10725390e-01,
        5.17363002e-01,  5.09156325e-01,  4.14374765e-01, -1.37055343e+00,
       -2.52756393e+00, -

In [99]:
quartiles = pd.qcut(data, 4, precision=2)

In [100]:
quartiles

[(0.72, 3.04], (0.72, 3.04], (0.72, 3.04], (-3.07, -0.68], (-0.68, 0.015], ..., (0.72, 3.04], (0.72, 3.04], (-0.68, 0.015], (-3.07, -0.68], (0.72, 3.04]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.07, -0.68] < (-0.68, 0.015] < (0.015, 0.72] < (0.72, 3.04]]

In [101]:
quartiles.value_counts()

(-3.07, -0.68]    250
(-0.68, 0.015]    250
(0.015, 0.72]     250
(0.72, 3.04]      250
Name: count, dtype: int64

In [103]:
pd.qcut(data, [0,0.1,0.5,0.9,1.]).value_counts()

(-3.061, -1.266]    100
(-1.266, 0.015]     400
(0.015, 1.227]      400
(1.227, 3.044]      100
Name: count, dtype: int64

In [129]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))

In [130]:
data.describe()

,0,1,2,3
count,1000.000000,1000.000000,1000.000000,1000.000000
mean,0.013165,-0.003330,-0.029027,-0.003246
std,1.000244,1.028619,1.036234,1.018807
min,-3.045902,-3.036792,-3.539812,-3.431820
25%,-0.635658,-0.675157,-0.731774,-0.696379
50%,0.008555,-0.011320,-0.054595,0.007655
75%,0.705397,0.697579,0.644509,0.692253
max,2.970247,3.339163,3.430107,3.103216


In [131]:
col = data[2]

In [132]:
col[col.abs() >3]

30    -3.539812
137    3.256573
322    3.423561
327    3.430107
887   -3.102559
Name: 2, dtype: float64

In [133]:
col[abs(col) >3]

30    -3.539812
137    3.256573
322    3.423561
327    3.430107
887   -3.102559
Name: 2, dtype: float64

In [138]:
data[(data.abs() >3).any(axis = "columns")]

,0,1,2,3
27,0.487249,-0.881105,0.151498,3.103216
30,-1.011141,-1.566926,-3.539812,-0.827922
57,-0.501571,3.339163,1.183119,0.601517
137,0.697314,-1.535528,3.256573,-0.659504
199,0.093080,-3.036792,0.160421,-0.486872
274,-0.449165,1.072948,0.285085,-3.051679
322,1.126269,0.130638,3.423561,0.855699
327,-0.316325,0.179506,3.430107,1.165584
386,-0.634798,-0.170982,0.025356,-3.030925
559,1.099518,1.541485,0.396349,-3.431820


In [139]:
data[(data.abs() >3).any(axis  = 'columns')]

,0,1,2,3
27,0.487249,-0.881105,0.151498,3.103216
30,-1.011141,-1.566926,-3.539812,-0.827922
57,-0.501571,3.339163,1.183119,0.601517
137,0.697314,-1.535528,3.256573,-0.659504
199,0.093080,-3.036792,0.160421,-0.486872
274,-0.449165,1.072948,0.285085,-3.051679
322,1.126269,0.130638,3.423561,0.855699
327,-0.316325,0.179506,3.430107,1.165584
386,-0.634798,-0.170982,0.025356,-3.030925
559,1.099518,1.541485,0.396349,-3.431820


In [141]:
data[(data.abs() >3)] = np.sign(data) *3


In [142]:
data[data.abs() > 3]

,0,1,2,3
0,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN
...,...,...,...,...
995,NaN,NaN,NaN,NaN
996,NaN,NaN,NaN,NaN
997,NaN,NaN,NaN,NaN
998,NaN,NaN,NaN,NaN


In [143]:

data[data.abs() > 3] = np.sign(data) * 3


In [144]:
data[data.abs() > 3]
data[data.abs() > 3] = np.sign(data) * 3


In [145]:
data.describe()

,0,1,2,3
count,1000.000000,1000.000000,1000.000000,1000.000000
mean,0.013211,-0.003633,-0.029495,-0.002911
std,1.000104,1.027463,1.030774,1.016660
min,-3.000000,-3.000000,-3.000000,-3.000000
25%,-0.635658,-0.675157,-0.731774,-0.696379
50%,0.008555,-0.011320,-0.054595,0.007655
75%,0.705397,0.697579,0.644509,0.692253
max,2.970247,3.000000,3.000000,3.000000


In [146]:
#perm and random sampling

In [147]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5, 7)))

In [148]:
df

,0,1,2,3,4,5,6
0,0,1,2,3,4,5,6
1,7,8,9,10,11,12,13
2,14,15,16,17,18,19,20
3,21,22,23,24,25,26,27
4,28,29,30,31,32,33,34


In [149]:
sampler = np.random.permutation(5)

In [150]:
sampler

array([2, 4, 3, 1, 0])

In [151]:
df.take(sampler)

,0,1,2,3,4,5,6
2,14,15,16,17,18,19,20
4,28,29,30,31,32,33,34
3,21,22,23,24,25,26,27
1,7,8,9,10,11,12,13
0,0,1,2,3,4,5,6


In [152]:
column_sampler = np.random.permutation(7)

In [153]:
column_sampler

array([0, 6, 4, 2, 3, 5, 1])

In [154]:
df.take(column_sampler, axis= "columns")

,0,6,4,2,3,5,1
0,0,6,4,2,3,5,1
1,7,13,11,9,10,12,8
2,14,20,18,16,17,19,15
3,21,27,25,23,24,26,22
4,28,34,32,30,31,33,29


In [155]:
df.sample( n =3)

,0,1,2,3,4,5,6
4,28,29,30,31,32,33,34
1,7,8,9,10,11,12,13
2,14,15,16,17,18,19,20


In [156]:
choices = pd.Series([5, 7, -1, 6, 4])

In [157]:
choices.sample(n =10, replace=True)

3    6
1    7
4    4
0    5
1    7
2   -1
1    7
2   -1
3    6
1    7
dtype: int64

In [159]:
#Computing Indicator/Dummy Variables


In [160]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
   .....:                    "data1": range(6)})

In [161]:
df

,key,data1
0,b,0
1,b,1
2,a,2
3,c,3
4,a,4
5,b,5


In [162]:
pd.get_dummies(df['key'], dtype= float)

,a,b,c
0,0.0,1.0,0.0
1,0.0,1.0,0.0
2,1.0,0.0,0.0
3,0.0,0.0,1.0
4,1.0,0.0,0.0
5,0.0,1.0,0.0


In [163]:
dummies = pd.get_dummies(df['key'], prefix= 'key', dtype= float)

In [164]:
dummies

,key_a,key_b,key_c
0,0.0,1.0,0.0
1,0.0,1.0,0.0
2,1.0,0.0,0.0
3,0.0,0.0,1.0
4,1.0,0.0,0.0
5,0.0,1.0,0.0


In [171]:
df_with_dummy = df[['data1']].join(dummies)

In [172]:
df_with_dummy

,data1,key_a,key_b,key_c
0,0,0.0,1.0,0.0
1,1,0.0,1.0,0.0
2,2,1.0,0.0,0.0
3,3,0.0,0.0,1.0
4,4,1.0,0.0,0.0
5,5,0.0,1.0,0.0


In [173]:
val = "a,b,  guido"

In [174]:
val.split(',')

['a', 'b', '  guido']

In [175]:
pieces = [x.strip() for x in val.split(',')]

In [176]:
pieces

['a', 'b', 'guido']

In [177]:
first, second, third = pieces

In [178]:
first + '::' +  second + '::' + third

'a::b::guido'

In [179]:
'::'.join(pieces)

'a::b::guido'

In [180]:
"guido" in val

True

In [181]:
val

'a,b,  guido'

In [182]:
val.index(',')

1

In [183]:
val.find(':')

-1

In [184]:
val.index(":")

ValueError: substring not found

In [185]:
val.count(",")

2

In [186]:
val.replace(',', '::')

'a::b::  guido'

In [187]:
import re

In [188]:
text = "foo    bar\t baz  \tqux"

In [189]:
re.split(r'\s+', text)

['foo', 'bar', 'baz', 'qux']

In [192]:
regex = re.compile(r"\s+")

In [193]:
regex.findall(text)

['    ', '\t ', '  \t']

In [194]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""

In [195]:
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

In [197]:
regex = re.compile(pattern, flags= re.IGNORECASE)

In [198]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [200]:
m = regex.search(text)

In [201]:
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [202]:
text[m.start():m.end()]

'dave@google.com'

In [203]:
regex.match(text)

In [205]:
print(regex.sub("REDACTED", text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED


In [206]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [207]:
regex = re.compile(pattern, flags=  re.IGNORECASE)

In [208]:
regex

re.compile(r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})',
           re.IGNORECASE|re.UNICODE)

In [209]:
m =regex.match("wesm@bright.net")

In [210]:
m

<re.Match object; span=(0, 15), match='wesm@bright.net'>

In [211]:
m.groups()

('wesm', 'bright', 'net')

In [213]:
print(regex.sub(r"Username: \1, Domain: \2, Suffix: \3", text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com


In [214]:
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com",
   .....:         "Rob": "rob@gmail.com", "Wes": np.nan}

In [215]:
data

{'Dave': 'dave@google.com',
 'Steve': 'steve@gmail.com',
 'Rob': 'rob@gmail.com',
 'Wes': nan}

In [216]:
data = pd.Series(data)

In [217]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [218]:
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [219]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [220]:
data_as_string_ext = data.astype('string')

In [222]:
data_as_string_ext.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

In [223]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [237]:
data.str.findall(pattern,flags= re.IGNORECASE).str[0]

Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                      NaN
dtype: object

In [225]:
matches = data.str.findall(pattern, flags=re.IGNORECASE).str[0]

In [226]:
matches

Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                      NaN
dtype: object

In [227]:
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [238]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [239]:
data.str.extract(pattern, flags= re.IGNORECASE)

,0,1,2
Dave,dave,google,com
Steve,steve,gmail,com
Rob,rob,gmail,com
Wes,NaN,NaN,NaN


In [240]:
values = pd.Series([0, 1, 0, 0] * 2)

In [241]:
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [242]:
dim = pd.Series(['apple', 'orange'])

In [243]:
dim

0     apple
1    orange
dtype: object

In [244]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

In [245]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2

In [246]:
fruits

['apple', 'orange', 'apple', 'apple', 'apple', 'orange', 'apple', 'apple']

In [247]:
N = len(fruits)

In [248]:
rng = np.random.default_rng(seed =12345)

In [249]:
 df = pd.DataFrame({'fruit': fruits,
   .....:                    'basket_id': np.arange(N),
   .....:                    'count': rng.integers(3, 15, size=N),
   .....:                    'weight': rng.uniform(0, 4, size=N)},
   .....:                   columns=['basket_id', 'fruit', 'count', 'weight'])

In [250]:
df

,basket_id,fruit,count,weight
0,0,apple,11,1.564438
1,1,orange,5,1.331256
2,2,apple,12,2.393235
3,3,apple,6,0.746937
4,4,apple,5,2.691024
5,5,orange,12,3.767211
6,6,apple,10,0.992983
7,7,apple,11,3.795525


In [255]:
type(df['fruit'])

pandas.core.series.Series

In [252]:
fruits_cat = df['fruit'].astype('category')

In [253]:
fruits_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [257]:
c = fruits_cat.array

In [258]:
type(c)

pandas.core.arrays.categorical.Categorical

In [259]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [260]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [261]:
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

In [262]:
df['fruit'] = df['fruit'].astype('category')

In [263]:
df['fruit']

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [264]:
my_categories = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar'])

In [265]:
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [267]:
categories = ['foo', 'bar', 'baz']

In [268]:
codes = [0, 1, 2, 0, 0, 1]

In [269]:
my_cat_2 = pd.Categorical.from_codes(codes, categories)

In [270]:
my_cat_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [272]:
ordered_cat = pd.Categorical.from_codes(codes, categories,
   .....:                                         ordered=True)

In [273]:
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [274]:
my_cat_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [275]:
rng = np.random.default_rng(seed=12345)
draws = rng.standard_normal(1000)

In [276]:
draws[:5]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [279]:
bins = pd.qcut(draws, 4, labels= ['Q1', 'Q2', 'Q3', 'Q4'])

In [280]:
bins

['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [282]:
bins.codes[:5]

array([0, 3, 0, 1, 1], dtype=int8)

In [283]:
bins = pd.Series(bins, name= 'quartile')

In [284]:
bins

0      Q1
1      Q4
2      Q1
3      Q2
4      Q2
       ..
995    Q3
996    Q3
997    Q2
998    Q3
999    Q2
Name: quartile, Length: 1000, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [286]:
results = (
    pd.Series(draws)
    .groupby(bins, observed=False)
    .agg(['count', 'min', 'max'])
    .reset_index()
)

In [287]:
results

,quartile,count,min,max
0,Q1,250,-3.119609,-0.678494
1,Q2,250,-0.673305,0.008009
2,Q3,250,0.018753,0.686183
3,Q4,250,0.688282,3.211418


In [288]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [289]:
N = 1_000_000

In [290]:
labels = pd.Series(['foo', 'bar', 'baz', 'qux'] * (N // 4))

In [291]:
labels

0         foo
1         bar
2         baz
3         qux
4         foo
         ... 
999995    qux
999996    foo
999997    bar
999998    baz
999999    qux
Length: 1000000, dtype: object

In [292]:
categories = labels.astype('category')

In [293]:
labels.memory_usage(deep=True)

52000132

In [294]:
categories.memory_usage(deep = True)

1000512

In [295]:
%time _=labels.astype('category')

CPU times: user 33.8 ms, sys: 7.42 ms, total: 41.2 ms
Wall time: 38.3 ms


In [296]:
%timeit labels.value_counts()

15.3 ms ± 58.2 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [297]:
%timeit categories.value_counts()

1.41 ms ± 8.75 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [298]:
s = pd.Series(['a', 'b', 'c', 'd'] * 2)

In [299]:
s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: object

In [301]:
cat_s = s.astype('category')

In [302]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [305]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [306]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [307]:
actual_categories = ['a', 'b', 'c', 'd', 'e']

In [308]:
cat_s2 = cat_s.cat.set_categories(actual_categories)

In [309]:
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [310]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
Name: count, dtype: int64

In [311]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
Name: count, dtype: int64

In [312]:
cat_s3 = cat_s[cat_s.isin(['a','b'])]

In [313]:
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [315]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): ['a', 'b']

In [316]:
cat_s = pd.Series(['a', 'b', 'c', 'd'] * 2, dtype='category')

In [317]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [320]:
pd.get_dummies(cat_s, dtype= 'float')

,a,b,c,d
0,1.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0
2,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,1.0
4,1.0,0.0,0.0,0.0
5,0.0,1.0,0.0,0.0
6,0.0,0.0,1.0,0.0
7,0.0,0.0,0.0,1.0
